title: "iCCF"
# remote_theme: just-the-docs/just-the-docs
theme: "just-the-docs"

color_scheme: "light"
search_enabled: true

# # Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/favicon.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

# For copy button on code
enable_copy_code_button: true

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  important:
    title: Important
    color: green

# Footer content
# appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2020-2025 João Faria. Distributed under the <a href=\"https://github.com/j-faria/iCCF/blob/master/LICENSE\">MIT license.</a>"
